### ISSUE TITLE
Several broken links

### ISSUE THREAD

**Issue by derrickburns** [solo-io/solo-docs#170]
To reproduce, run:  https://github.com/stevenvachon/broken-link-checker
```
blc -ro https://gloo.solo.io
```
[broken.txt](https://github.com/solo-io/solo-docs/files/2974678/broken.txt)

**Comment by christian-posta** [comment]
Yah just noticed the links on https://gloo.solo.io/v1/github.com/solo-io/gloo/projects/gloo/api/v1/proxy.proto.sk/ are broken as well. Many thanks @derrickburns we'll fix this ASAP. 

@rettori @rickducott

**Comment by christian-posta** [comment]
Think we should make this part of the `make site` target?

**Comment by christian-posta** [comment]
So I'm working on fixing the links right now... I'll add a make target that can discover broken links, but we should come up with a suitable solution for the CI part of the process.

**Comment by christian-posta** [comment]
@derrickburns Thanks again for opening this. We should have them all sorted now with PR #216.
Also added a make target to find broken links: https://github.com/solo-io/solo-docs/pull/216/files#diff-ac848e42aec35253d92828ff2c6e1a42R17

Let us know if you notice anything else about the docs.
