### ISSUE TITLE
glooe link downloads old version of glooctl

### ISSUE THREAD

**Issue by mitchdraft** [solo-io/solo-docs#327]
https://gloo.solo.io/enterprise/installation/install_glooctl/

```bash
glooctl --version
glooctl enterprise edition version 0.13.9
```

latest release is `0.13.15`
https://github.com/solo-io/solo-projects/releases

I noticed because the redis image pull failed

## Potential fixes:
- point to a "latest" release
  - Not sure if google storage supports this
- point to the github releases page
  - lose the one-click download feature
- implement a download page with redirects?
  - https://github.com/solo-io/build/issues/13#issuecomment-489128084

What do you think @scranton @rickducott

**Comment by mitchdraft** [comment]
Note, the mac os download link looks like this:

https://storage.googleapis.com/glooctl-enterprise/051F7858-30A6-42CA-8EF2-9012D521358A/glooctl-darwin-amd64

**Comment by rickducott** [comment]
This was fixed,

**Comment by rickducott** [comment]
Regarding the specifics above, we can't point to a GH releases page because the enterprise CLI releases in a private repo. But we already have a redirect in Google storage / in the docs, we just need to make sure we're updating the artifacts -- which we are handling elsewhere.
