### ISSUE TITLE
Add HubSpot Tracking code to docs

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/solo-docs#606]
I think this was removed at some point -- please add back to all docs 

<script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/5130874.js"></script>

**Comment by mitchdraft** [comment]
this is still on our API docs, but not on our hand-written docs

**Comment by bettyjunod** [comment]
Is it possible to add to the header (style) so it doesn't need to be added on a per page basis but is built into the theme?

**Comment by mitchdraft** [comment]
yep, that's exactly what I'll do

**Comment by mitchdraft** [comment]
done with the exact script cited in the task description
