### ISSUE TITLE
Add Google Analytics Tag to all docs

### ISSUE THREAD

**Issue by bettyjunod** [solo-io/solo-docs#607]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-149486620-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-149486620-1');
</script>

**Comment by mitchdraft** [comment]
could have been removed here:
https://github.com/solo-io/hugo-theme-soloio/commit/4f9f8bdc5b389b803559f2c0c930e6f822f51996#diff-20207d833e23331bad407e87a03d018cL2

should be easy to restore

@bettyjunod , could you confirm the Google Analytics tag? We are currently referencing another tag:
```
glooshot/docs.toml
9:googleAnalytics = "UA-101654320-1"

squash/docs.toml
9:googleAnalytics = "UA-101654320-1"

supergloo/docs.toml
9:googleAnalytics = "UA-101654320-1"

testrepo/docs.toml
9:googleAnalytics = "UA-101654320-1"

sqoop/docs.toml
9:googleAnalytics = "UA-101654320-1"

gloo/docs.toml
9:googleAnalytics = "UA-101654320-1"

```

**Comment by bettyjunod** [comment]
ah ok - let me see if I can recover that account.

**Comment by mitchdraft** [comment]
done with the exact script cited in the task description
