### ISSUE TITLE
Wrong path in Squash documentation for remote path

### ISSUE THREAD

**Issue by olaf-meyer** [solo-io/solo-docs#646]
When I tested the  Squash demo application in Visual Studio Code like described in the file squash/docs/overview/_index.md, I can't set a break point and get this error message:
```bash
SetBreakPointsRequest
All cleared
Creating on: /home/olaf/projects/squash/contrib/example/service1/main.go (/home/yuval/go/src/github.com/solo-io/squash/contrib/example/contrib/example/service1/main.go) :88
Error on CreateBreakpoint: could not find /home/yuval/go/src/github.com/solo-io/squash/contrib/example/contrib/example/service1/main.go:88
All set:[null]
```

If I changed the remote path in Visual Studio Code to `/home/yuval/go/src/github.com/solo-io/squash/` I can set breakpoints and debug the application. Is there something special about my Visual Studio Code setup?

**Comment by mitchdraft** [comment]
Sorry for the confusion @olaf-meyer , glad you got the demo working.

The remote path depends on which directory is in the root of your VSCode session (which directory you "open" when starting a new session).

The example cites this remote path: `/home/yuval/go/src/github.com/solo-io/squash/contrib/example/`, which assumes that you opened your session to the `<parent_dir>/squash/contrib/example/` directory - perhaps this point should be clarified.

We have additional notes on source code mapping here: https://squash.solo.io/configuration/#source-code-mapping

Essentially, VSCode appends the workspace-relative path to the substitution string.

I'm happy to update the docs and would appreciate your suggestions. Given these notes and your perspective as a new user, how do you recommend we make this more clear?

**Comment by olaf-meyer** [comment]
Hello,

thank you for the clarification. I read the article about the code mapping and at that time it made perfect sense to me. The point that I missed is that the remote path is depending how your workspace looks like in Visual Studio Code. If your workspace contains only the folder with the example go file, then the remote path is like `/home/yuval/go/src/github.com/solo-io/squash/contrib/example/service1/`. If your workspace contains the complete squash git repo than the remote path is `/home/yuval/go/src/github.com/solo-io/squash/`. The "missing" sub path to the source code is defined by the folder structure in the workspace.  

IMHO it would make sense to mention that the remote path is depending on the `start point` of your work space. Is there by chance a way to determine the remote path before I start to debug a pod?

**Comment by olaf-meyer** [comment]
Should I close the issue?
