### ISSUE TITLE
Gloo: link broken in "multiple-gloo" docs

### ISSUE THREAD

**Issue by Dominik-K** [solo-io/solo-docs#648]
At https://docs.solo.io/gloo/latest/advanced_configuration/multiple-gloo-installs/#scoping-gloo-to-specific-namespaces, "watchNamespaces setting" link is broken. I guess it's a bug in the doc creation automation.

**Comment by mitchdraft** [comment]
thanks @Dominik-K ! fix should be out soon

**Comment by Dominik-K** [comment]
Fixed with https://github.com/solo-io/gloo/pull/1648
